import type {
  Person,
  RealtimeEvent,
  Recording,
  Report,
  Room,
  SpeakerRequest,
  SystemJob,
} from "@/types/wavecast";

const avatar = (id: number) => `https://i.pravatar.cc/160?img=${id}`;

export const alex: Person = {
  id: "user_brian",
  name: "Brian Miller",
  username: "brian.miller",
  role: "Host",
  avatar: avatar(12),
  online: true,
};

export const people: Person[] = [
  {
    id: "user_alice",
    name: "Alice Johnson",
    username: "alice.johnson",
    role: "Host",
    avatar: avatar(47),
    isFriend: true,
    online: true,
    isSpeaking: true,
  },
  {
    id: "user_brian",
    name: "Brian Miller",
    username: "brian.miller",
    role: "Speaker",
    avatar: avatar(12),
    isFriend: true,
    online: true,
    isSpeaking: false,
  },
  {
    id: "user_carol",
    name: "Carol Davis",
    username: "carol.davis",
    role: "Speaker",
    avatar: avatar(32),
    isFriend: true,
    online: true,
    isSpeaking: false,
  },
  {
    id: "user_sarah",
    name: "Sarah Wilson",
    username: "sarah.wilson",
    role: "Listener",
    avatar: avatar(13),
    online: true,
  },
  {
    id: "user_james",
    name: "James Lee",
    username: "james.lee",
    role: "Listener",
    avatar: avatar(14),
    online: true,
  },
  {
    id: "user_priya",
    name: "Priya Shah",
    username: "priya.shah",
    role: "Listener",
    avatar: avatar(44),
    online: true,
  },
  {
    id: "user_wade",
    name: "Wade Warren",
    username: "wade.warren",
    role: "Listener",
    avatar: avatar(15),
    isFriend: true,
    online: true,
  },
  {
    id: "user_jenny",
    name: "Jenny Wilson",
    username: "jenny.wilson",
    role: "Listener",
    avatar: avatar(49),
    online: true,
  },
  {
    id: "user_arla",
    name: "Arlene McCoy",
    username: "arlene.mccoy",
    role: "Listener",
    avatar: avatar(5),
    isFriend: true,
    online: true,
  },
  {
    id: "user_cody",
    name: "Cody Fisher",
    username: "cody.fisher",
    role: "Listener",
    avatar: avatar(7),
    online: true,
  },
  {
    id: "user_dianne",
    name: "Dianne Russell",
    username: "dianne.russell",
    role: "Speaker",
    avatar: avatar(25),
    isFriend: true,
    online: false,
  },
  {
    id: "user_esther",
    name: "Esther Howard",
    username: "esther.howard",
    role: "Speaker",
    avatar: avatar(31),
    online: true,
  },
  {
    id: "user_floyd",
    name: "Floyd Miles",
    username: "floyd.miles",
    role: "Moderator",
    avatar: avatar(20),
    online: true,
  },
  {
    id: "user_brooklyn",
    name: "Brooklyn Simmons",
    username: "brooklyn.simmons",
    role: "Listener",
    avatar: avatar(18),
    online: true,
  },
];

export const room: Room = {
  id: "room_0TH0XSZ73XK0R6",
  title: "The Future of AI in Everyday Life",
  topic: "Tech Talk",
  status: "live",
  listenerCount: 1197,
  speakerCount: 78,
  startedAt: "00:23:45 ago",
  duration: "01:23:45",
  recording: true,
  hlsStatus: "Healthy",
  language: "English",
  owner: alex,
  speakers: [people[0], people[1], people[2]],
  listeners: people.slice(1, 14),
};

export const rooms: Room[] = [
  {
    ...room,
    listenerCount: 1248,
    speakerCount: 78,
    startedAt: "00:23:45 ago",
    duration: "01:23:45",
  },
  {
    ...room,
    id: "room_0THOX4M6JHSK2Q",
    title: "Building in Public: Lessons Learned",
    topic: "Entrepreneurship",
    listenerCount: 412,
    speakerCount: 24,
    startedAt: "01:12:10 ago",
    duration: "45:30",
  },
  {
    ...room,
    id: "room_0IHIC3YF2Q7LBD",
    title: "Open discussion: Startups & VC",
    topic: "Business",
    listenerCount: 623,
    speakerCount: 45,
    startedAt: "02:05:27 ago",
    duration: "32:10",
  },
  {
    ...room,
    id: "room_01HX2KJ28MN",
    title: "SaaS Growth Tactics That Work",
    topic: "Marketing",
    status: "scheduled",
    listenerCount: 184,
    speakerCount: 6,
    startedAt: "Today, 7:00 PM",
    duration: "-",
    recording: false,
    hlsStatus: "Off",
  },
  {
    ...room,
    id: "room_0IHXUTNQSP4B",
    title: "Morning Mindset & Productivity",
    topic: "Health",
    status: "scheduled",
    listenerCount: 92,
    speakerCount: 4,
    startedAt: "Tomorrow, 9:00 AM",
    duration: "-",
    recording: false,
    hlsStatus: "Off",
  },
  {
    ...room,
    id: "room_0EDU41K8Q7",
    title: "Learning Systems for Busy Teams",
    topic: "Education",
    status: "scheduled",
    listenerCount: 136,
    speakerCount: 5,
    startedAt: "Tomorrow, 2:30 PM",
    duration: "-",
    recording: false,
    hlsStatus: "Off",
  },
  {
    ...room,
    id: "room_0MUS91N4X2",
    title: "Indie Music Discovery Hour",
    topic: "Music",
    status: "scheduled",
    listenerCount: 248,
    speakerCount: 8,
    startedAt: "Friday, 6:00 PM",
    duration: "-",
    recording: false,
    hlsStatus: "Off",
  },
  {
    ...room,
    id: "room_0LIF72P9A3",
    title: "Reset Routines for Remote Work",
    topic: "Lifestyle",
    status: "scheduled",
    listenerCount: 117,
    speakerCount: 3,
    startedAt: "Saturday, 11:00 AM",
    duration: "-",
    recording: false,
    hlsStatus: "Off",
  },
  {
    ...room,
    id: "room_0BUS88V6C1",
    title: "Operator Roundtable: Pricing Signals",
    topic: "Business",
    status: "scheduled",
    listenerCount: 312,
    speakerCount: 9,
    startedAt: "Sunday, 4:00 PM",
    duration: "-",
    recording: false,
    hlsStatus: "Off",
  },
  {
    ...room,
    id: "room_01THWXY7632T2",
    title: "Product Design Trends 2024",
    topic: "Design",
    status: "finished",
    listenerCount: 856,
    speakerCount: 56,
    startedAt: "May 17, 11:00 AM",
    duration: "01:15:22",
    recording: false,
    hlsStatus: "Off",
  },
];

export const speakerRequests: SpeakerRequest[] = [
  {
    id: "request_wade",
    person: people[6],
    message: "I'd love to share my thoughts on this topic.",
    requestedAt: "2m ago",
    status: "pending",
  },
  {
    id: "request_jenny",
    person: people[7],
    message: "Can I discuss the real-world use cases?",
    requestedAt: "4m ago",
    status: "pending",
  },
];

export const jobs: SystemJob[] = [
  {
    id: "job_0TH0XSZ73XK0R6",
    type: "generate_report",
    status: "Running",
    createdAt: "2m ago",
  },
  {
    id: "job_0H4M6JHSK2Q",
    type: "finalize_recording",
    status: "Completed",
    createdAt: "10m ago",
  },
  {
    id: "job_0IHIC3YF2Q7LBD",
    type: "expire_sessions",
    status: "Completed",
    createdAt: "15m ago",
  },
  {
    id: "job_01H2KJ28MN",
    type: "dispatch_event",
    status: "Retrying",
    createdAt: "18m ago",
  },
  {
    id: "job_0IHXUTNQSP4B",
    type: "sync_analytics",
    status: "Failed",
    createdAt: "25m ago",
  },
];

export const reports: Report[] = [
  {
    id: "report_01HXSZ73XK0R6",
    room: "The Future of AI in Everyday Life",
    status: "Ready",
    createdAt: "2m ago",
  },
  {
    id: "report_01H4M6JH1K2Q",
    room: "Building in Public: Lessons Learned",
    status: "Ready",
    createdAt: "15m ago",
  },
  {
    id: "report_0HIC3YFQ7LBD",
    room: "Open discussion: Startups & VC",
    status: "Generating",
    createdAt: "22m ago",
  },
  {
    id: "report_01HX2KJ28MN",
    room: "SaaS Growth Tactics That Work",
    status: "Failed",
    createdAt: "1h ago",
  },
  {
    id: "report_01HXUTNQSP4B",
    room: "Morning Mindset & Productivity",
    status: "Ready",
    createdAt: "1h ago",
  },
];

export const recordings: Recording[] = [
  {
    id: "rec_0TH0XSZ73XK0R6",
    room: "The Future of AI in Everyday Life",
    duration: "01:23:45",
    size: "124.4 MB",
    status: "Ready",
  },
  {
    id: "rec_0H4M6JHSK2Q",
    room: "Building in Public",
    duration: "00:45:30",
    size: "86.3 MB",
    status: "Ready",
  },
  {
    id: "rec_0IHIC3YF2Q7LBD",
    room: "Open discussion",
    duration: "00:32:10",
    size: "60.1 MB",
    status: "Processing",
  },
  {
    id: "rec_01H2KJ28MN",
    room: "Product Design Trends",
    duration: "01:15:22",
    size: "110.3 MB",
    status: "Ready",
  },
];

export const realtimeEvents: RealtimeEvent[] = [
  {
    time: "12:30:45",
    event: "speaker.joined",
    room: "The Future of AI in Everyday Life",
    user: "user_877u24",
    details: "Brian Miller joined the stage",
  },
  {
    time: "12:30:30",
    event: "listener.joined",
    room: "The Future of AI in Everyday Life",
    user: "user_a7h3d3",
    details: "Listener joined",
  },
  {
    time: "12:30:15",
    event: "request.approved",
    room: "The Future of AI in Everyday Life",
    user: "user_3x4ds",
    details: "Jenny Wilson approved",
  },
  {
    time: "12:30:10",
    event: "message.sent",
    room: "The Future of AI in Everyday Life",
    user: "user_64edf6",
    details: "Great insights so far!",
  },
  {
    time: "12:30:05",
    event: "listener.left",
    room: "Building in Public",
    user: "user_Mgfh8",
    details: "Listener left",
  },
];

export const analyticsCards = [
  { label: "Total Listeners", value: "12,456", delta: "+12.5%" },
  { label: "Total Rooms", value: "128", delta: "+8.3%" },
  { label: "Total Speakers", value: "342", delta: "+15.2%" },
  { label: "Total Duration", value: "240h 32m", delta: "+10.7%" },
];

export const chartData = [
  { label: "May 12", listeners: 500, speakers: 18 },
  { label: "May 13", listeners: 920, speakers: 26 },
  { label: "May 14", listeners: 1480, speakers: 47 },
  { label: "May 15", listeners: 1160, speakers: 33 },
  { label: "May 16", listeners: 1530, speakers: 52 },
  { label: "May 17", listeners: 1330, speakers: 42 },
  { label: "May 18", listeners: 1690, speakers: 56 },
];

export const listenerChartData = [
  { label: "00:00", value: 180 },
  { label: "00:20", value: 520 },
  { label: "00:40", value: 650 },
  { label: "01:00", value: 760 },
  { label: "01:20", value: 1248 },
];

export const speakerBarData = [
  { label: "00:00", value: 24 },
  { label: "00:20", value: 42 },
  { label: "00:40", value: 51 },
  { label: "01:00", value: 38 },
  { label: "01:20", value: 78 },
];

export const waveform = [
  34, 55, 29, 64, 42, 75, 51, 88, 47, 70, 39, 62, 82, 45, 58, 33, 73, 52, 86, 31, 54, 69, 43, 77,
  36, 61, 49, 84, 57, 35, 68, 91,
];
